### ISSUE TITLE
Discover Command triggers an error in

### ISSUE THREAD

**Issue by schliesser** [tollwerk/TYPO3-ext-tw_componentlibrary#18]
If you call the typo3-console with `vendor/bin/typo3cms` or `vendor/bin/typo3cms list` an error is thrown:
```
/var/www/html$ typo3cms
TYPO3 Console 6.1.0
TYPO3 CMS 10.4.3 (Application Context: Development)

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug


                                                                                                                                           
  [ TYPO3\CMS\Core\Error\Exception ]                                                                                                       
  Warning: Invalid argument supplied for foreach() in /var/www/html/public/typo3/sysext/core/Classes/Utility/RootlineUtility.php line 289  
                                                                                                                                           
```

I've traced it down to the contructor of the discover command. The same error is thrown by direct call of this command (`vendor/bin/typo3cms component:discover`).

If I call the command via `vendor/bin/typo3 component:discover` I just get an empty array.

Tested with TYPO3 10.4.3; TYPO3-Console 6.1.0 & latest version from master branch of tw_componentlibrary.

**Comment by jkphl** [comment]
@schliesser Thanks for reporting.

Just to clarify: Calling `typo3cms` isn't TYPO3 core functionality but involves the third party extension `typo3-console`, correct? If so, I might have a look at some point, but we usually don't use this console extension and the component library is far from being optimized for use in combination.

Regarding the empty array: Please make sure you enabled component export in the TYPO3 constants of your extension, see screenshot. The flag is mandatory for some time already, but it's possible that it's not properly documented yet. Sorry for that.

![Schnappschuss_060420_025306_PM](https://user-images.githubusercontent.com/4446936/83759024-3e022800-a673-11ea-90d7-b7d262dcecd7.jpg)

**Comment by schliesser** [comment]
@jkphl Thank you for the hint with the typoscript feature :-)

I added an PR to fixe the console issues. We use the `helhum/typo3-console` in nearly all projects.
